package espanhol.grammars;

/**
 * This class is generated automatically.
 * Only exit this class for Dynamic External grammars and override the method String getURL().
 * Last generated by Orchestration Designer at: 20 DE ABRIL DE 2016 15H53MIN5S BRT
 */
public class ColetaSenhaResgate extends com.avaya.sce.runtime.Grammar {

    //{{START:CLASS:FIELDS
    //}}END:CLASS:FIELDS

    /**
    * Constructor for ColetaSenhaResgate.
    */
    public ColetaSenhaResgate() {
		//{{START:CLASS:CONSTRUCTOR
        super();
        setRootLanguage("es-la");
        setMode("dtmf");
        setBuiltin(true);
        setBuiltinMode("dtmf");
        setType("digits");
        setOptions("minlength=6;maxlength=8");
		//}}END:CLASS:CONSTRUCTOR
    }

}

