package portugues.phrasesets;

/**
 * This phraseset class will be automatically populated with data from the 
 * phraseset project file.  Manual edits should only be outside of the tag 
 * areas or overridden methods. 
 * Class created on: 
 * Last generated by Orchestration Designer at: 16 DE ABRIL DE 2016 0H0MIN22S BRT
 */
public class FrasesMultiplus extends com.avaya.sce.runtime.Phraseset { 

	//{{START:CLASS:FIELDS
	private static final com.avaya.sce.runtime.Phraseset.PhraseMap PHRASE_MAP;
	//}}END:CLASS:FIELDS

	/**
	 * Static initializer
	 */
	static {
		//{{START:PHRASESET:STATIC

		// Create the phrase map, then populate with phrases
		PHRASE_MAP = new com.avaya.sce.runtime.Phraseset.PhraseMap(60);
		com.avaya.sce.runtime.Phrase phrase;

		// phrase: PT0a
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "PT0a", "PT0a.wav", ""); 

		// phrase: ING0a
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ING0a", "ING0a.wav", ""); 

		// phrase: ESP0a
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ESP0a", "ESP0a.wav", ""); 

		// phrase: MP0
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "MP0", "PTMP0.wav", ""); 

		// phrase: MP1
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "MP1", "PTMP1.wav", ""); 

		// phrase: MP2
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "MP2", "PTMP2.wav", ""); 

		// phrase: MP3
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "MP3", "PTMP3.wav", ""); 

		// phrase: MP4
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "MP4", "PTMP4.wav", ""); 

		// phrase: MP5
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "MP5", "PTMP5.wav", ""); 

		// phrase: MP9
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "MP9", "PTMP9.wav", ""); 

		// phrase: MPOuvir
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "MPOuvir", "PTMPOuvir.wav", ""); 

		// phrase: OpInv
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "OpInv", "PTOpInv.wav", ""); 

		// phrase: 11d
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "11d", "PT11d.wav", ""); 

		// phrase: 11e
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "11e", "PT11e.wav", ""); 

		// phrase: 11f
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "11f", "PT11f.wav", ""); 

		// phrase: 11i
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "11i", "PT11i.wav", ""); 

		// phrase: VoltarMenuInicial
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "VoltarMenuInicial", "PTVoltarMenuInicial.wav", ""); 

		// phrase: SemDuvida
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "SemDuvida", "PTSemDuvida.wav", ""); 

		// phrase: DigCPF
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "DigCPF", "PTDigCPF.wav", ""); 

		// phrase: EsqCPF
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "EsqCPF", "PTEsqCPF.wav", ""); 

		// phrase: 10a
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "10a", "PT10a.wav", ""); 

		// phrase: 111a
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "111a", "PT111a.wav", ""); 

		// phrase: 112a
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "112a", "PT112a.wav", ""); 

		// phrase: 113a
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "113a", "PT113a.wav", ""); 

		// phrase: VoltarMenuAnterior
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "VoltarMenuAnterior", "PTVoltarMenuAnterior.wav", ""); 

		// phrase: 21d
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "21d", "PT21d.wav", ""); 

		// phrase: 21e
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "21e", "PT21e.wav", ""); 

		// phrase: 21f
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "21f", "PT21f.wav", ""); 

		// phrase: 21g
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "21g", "PT21g.wav", ""); 

		// phrase: MPEncer
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "MPEncer", "PTMPEncer.wav", ""); 

		//}}END:PHRASESET:STATIC
	}
	/**
	 * Returns the Phrase with the given name.  To override the
	 * behavior and dynamically return a different Phrase object,
	 * override the method "hookGetPhrase(...)".
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 20 DE ABRIL DE 2016 9H24MIN53S BRT
	 * @see com.avaya.sce.runtime.Phraseset#getPhrase(String) 
	 */ 
	public com.avaya.sce.runtime.Phrase getPhrase(String phraseName) {
		return(getPhrase(FrasesMultiplus.PHRASE_MAP, phraseName));
	}
}
