package portugues.phrasesets;

/**
 * This phraseset class will be automatically populated with data from the 
 * phraseset project file.  Manual edits should only be outside of the tag 
 * areas or overridden methods. 
 * Class created on: 
 * Last generated by Orchestration Designer at: 16 DE ABRIL DE 2016 0H0MIN22S BRT
 */
public class FrasesMultiplus extends com.avaya.sce.runtime.Phraseset { 

	//{{START:CLASS:FIELDS
	private static final com.avaya.sce.runtime.Phraseset.PhraseMap PHRASE_MAP;
	//}}END:CLASS:FIELDS

	/**
	 * Static initializer
	 */
	static {
		//{{START:PHRASESET:STATIC

		// Create the phrase map, then populate with phrases
		PHRASE_MAP = new com.avaya.sce.runtime.Phraseset.PhraseMap(80);
		com.avaya.sce.runtime.Phrase phrase;

		// phrase: MenuIdioma
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "MenuIdioma", "EscolhaLinguagem.wav", ""); 

		// phrase: PTMP0
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "PTMP0", "PTMP0.wav", ""); 

		// phrase: PTMP1
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "PTMP1", "PTMP1.wav", ""); 

		// phrase: PTMP2
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "PTMP2", "PTMP2.wav", ""); 

		// phrase: PTMP3
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "PTMP3", "PTMP3.wav", ""); 

		// phrase: PTMP4
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "PTMP4", "PTMP4.wav", ""); 

		// phrase: PTMP5
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "PTMP5", "PTMP5.wav", ""); 

		// phrase: PTMP9
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "PTMP9", "PTMP9.wav", ""); 

		// phrase: PTMPOuvir
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "PTMPOuvir", "PTMPOuvir.wav", ""); 

		// phrase: INGMP0
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "INGMP0", "INGMP0.wav", ""); 

		// phrase: INGMP1
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "INGMP1", "INGMP1.wav", ""); 

		// phrase: INGMP2
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "INGMP2", "INGMP2.wav", ""); 

		// phrase: INGMP3
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "INGMP3", "INGMP3.wav", ""); 

		// phrase: INGMP4
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "INGMP4", "INGMP4.wav", ""); 

		// phrase: INGMP5
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "INGMP5", "INGMP5.wav", ""); 

		// phrase: INGMP9
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "INGMP9", "INGMP9.wav", ""); 

		// phrase: INGMPOuvir
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "INGMPOuvir", "INGMPOuvir.wav", ""); 

		// phrase: ESPMP0
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ESPMP0", "ESPMP0.wav", ""); 

		// phrase: ESPMP1
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ESPMP1", "ESPMP1.wav", ""); 

		// phrase: ESPMP2
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ESPMP2", "ESPMP2.wav", ""); 

		// phrase: ESPMP3
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ESPMP3", "ESPMP3.wav", ""); 

		// phrase: ESPMP4
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ESPMP4", "ESPMP4.wav", ""); 

		// phrase: ESPMP5
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ESPMP5", "ESPMP5.wav", ""); 

		// phrase: ESPMP9
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ESPMP9", "ESPMP9.wav", ""); 

		// phrase: ESPMPOuvir
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ESPMPOuvir", "ESPMPOuvir.wav", ""); 

		// phrase: PTOpInv
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "PTOpInv", "PTOpInv.wav", ""); 

		// phrase: INGOpInv
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "INGOpInv", "INGOpInv.wav", ""); 

		// phrase: ESPOpInv
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ESPOpInv", "ESPOpInv.wav", ""); 

		// phrase: PTMPEncer
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "PTMPEncer", "PTMPEncer.wav", ""); 

		// phrase: INGMPEncer
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "INGMPEncer", "INGMPEncer.wav", ""); 

		// phrase: ESPMPEncer
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ESPMPEncer", "ESPMPEncer.wav", ""); 

		// phrase: ESPDigCPF
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ESPDigCPF", "ESPDigCPF.wav", ""); 

		// phrase: INGDigCPF
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "INGDigCPF", "INGDigCPF.wav", ""); 

		// phrase: PTDigCPF
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "PTDigCPF", "PTDigCPF.wav", ""); 

		// phrase: ESP10a
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ESP10a", "ESP10a.wav", ""); 

		// phrase: ING10a
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ING10a", "ING10a.wav", ""); 

		// phrase: PT10a
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "PT10a", "PT10a.wav", ""); 

		// phrase: PTEsqCPF
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "PTEsqCPF", "PTEsqCPF.wav", ""); 

		// phrase: INGEsqCPF
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "INGEsqCPF", "INGEsqCPF.wav", ""); 

		// phrase: ESPEsqCPF
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ESPEsqCPF", "ESPEsqCPF.wav", ""); 

		//}}END:PHRASESET:STATIC
	}
	/**
	 * Returns the Phrase with the given name.  To override the
	 * behavior and dynamically return a different Phrase object,
	 * override the method "hookGetPhrase(...)".
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 16 DE ABRIL DE 2016 18H57MIN35S BRT
	 * @see com.avaya.sce.runtime.Phraseset#getPhrase(String) 
	 */ 
	public com.avaya.sce.runtime.Phrase getPhrase(String phraseName) {
		return(getPhrase(FrasesMultiplus.PHRASE_MAP, phraseName));
	}
}
