package portugues.phrasesets;

/**
 * This phraseset class will be automatically populated with data from the 
 * phraseset project file.  Manual edits should only be outside of the tag 
 * areas or overridden methods. 
 * Class created on: 
 * Last generated by Orchestration Designer at: 19 DE ABRIL DE 2016 16H55MIN22S BRT
 */
public class std_pt_br extends com.avaya.sce.runtime.Phraseset { 

	//{{START:CLASS:FIELDS
	private static final com.avaya.sce.runtime.Phraseset.PhraseMap PHRASE_MAP;
	//}}END:CLASS:FIELDS

	/**
	 * Static initializer
	 */
	static {
		//{{START:PHRASESET:STATIC

		// Create the phrase map, then populate with phrases
		PHRASE_MAP = new com.avaya.sce.runtime.Phraseset.PhraseMap(998);
		com.avaya.sce.runtime.Phrase phrase;

		// phrase: std_a
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_a", "0001.wav", ":a"); 

		// phrase: std_b
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_b", "0002.wav", ":b"); 

		// phrase: std_c
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_c", "0003.wav", ":c"); 

		// phrase: std_d
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_d", "0004.wav", ":d"); 

		// phrase: std_e
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_e", "0005.wav", ":e"); 

		// phrase: std_f
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_f", "0006.wav", ":f"); 

		// phrase: std_g
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_g", "0007.wav", ":g"); 

		// phrase: std_h
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_h", "0008.wav", ":h"); 

		// phrase: std_i
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_i", "0009.wav", ":i"); 

		// phrase: std_j
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_j", "0010.wav", ":j"); 

		// phrase: std_k
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_k", "0011.wav", ":k"); 

		// phrase: std_l
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_l", "0012.wav", ":l"); 

		// phrase: std_m
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_m", "0013.wav", ":m"); 

		// phrase: std_n
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_n", "0014.wav", ":n"); 

		// phrase: std_o
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_o", "0015.wav", ":o"); 

		// phrase: std_p
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_p", "0016.wav", ":p"); 

		// phrase: std_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_q", "0017.wav", ":q"); 

		// phrase: std_r
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_r", "0018.wav", ":r"); 

		// phrase: std_s
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_s", "0019.wav", ":s"); 

		// phrase: std_t
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_t", "0020.wav", ":t"); 

		// phrase: std_u
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_u", "0021.wav", ":u"); 

		// phrase: std_v
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_v", "0022.wav", ":v"); 

		// phrase: std_w
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_w", "0023.wav", ":w"); 

		// phrase: std_x
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_x", "0024.wav", ":x"); 

		// phrase: std_y
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_y", "0025.wav", ":y"); 

		// phrase: std_z
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_z", "0026.wav", ":z"); 

		// phrase: std_minus
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_minus", "0029.wav", ":-"); 

		// phrase: std_0
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_0", "0030.wav", ":0"); 

		// phrase: std_1
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_1", "0031.wav", ":1"); 

		// phrase: std_2
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_2", "0032.wav", ":2"); 

		// phrase: std_3
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_3", "0033.wav", ":3"); 

		// phrase: std_4
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_4", "0034.wav", ":4"); 

		// phrase: std_5
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_5", "0035.wav", ":5"); 

		// phrase: std_6
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_6", "0036.wav", ":6"); 

		// phrase: std_7
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_7", "0037.wav", ":7"); 

		// phrase: std_8
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_8", "0038.wav", ":8"); 

		// phrase: std_9
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_9", "0039.wav", ":9"); 

		// phrase: std_10
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_10", "0040.wav", ":10"); 

		// phrase: std_11
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_11", "0041.wav", ":11"); 

		// phrase: std_12
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_12", "0042.wav", ":12"); 

		// phrase: std_13
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_13", "0043.wav", ":13"); 

		// phrase: std_14
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_14", "0044.wav", ":14"); 

		// phrase: std_15
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_15", "0045.wav", ":15"); 

		// phrase: std_16
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_16", "0046.wav", ":16"); 

		// phrase: std_17
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_17", "0047.wav", ":17"); 

		// phrase: std_18
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_18", "0048.wav", ":18"); 

		// phrase: std_19
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_19", "0049.wav", ":19"); 

		// phrase: std_20
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_20", "0050.wav", ":20"); 

		// phrase: std_30
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_30", "0051.wav", ":30"); 

		// phrase: std_40
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_40", "0052.wav", ":40"); 

		// phrase: std_50
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_50", "0053.wav", ":50"); 

		// phrase: std_60
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_60", "0054.wav", ":60"); 

		// phrase: std_70
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_70", "0055.wav", ":70"); 

		// phrase: std_80
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_80", "0056.wav", ":80"); 

		// phrase: std_90
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_90", "0057.wav", ":90"); 

		// phrase: std_100
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_100", "0058.wav", ":100"); 

		// phrase: std_200
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_200", "0059.wav", ":200"); 

		// phrase: std_300
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_300", "0060.wav", ":300"); 

		// phrase: std_400
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_400", "0061.wav", ":400"); 

		// phrase: std_500
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_500", "0062.wav", ":500"); 

		// phrase: std_600
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_600", "0063.wav", ":600"); 

		// phrase: std_700
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_700", "0064.wav", ":700"); 

		// phrase: std_800
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_800", "0065.wav", ":800"); 

		// phrase: std_900
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_900", "0066.wav", ":900"); 

		// phrase: std_100_plus
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_100_plus", "0067.wav", ":100+"); 

		// phrase: std_a_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_a_dot", "0071.wav", ":a."); 

		// phrase: std_b_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_b_dot", "0072.wav", ":b."); 

		// phrase: std_c_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_c_dot", "0073.wav", ":c."); 

		// phrase: std_d_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_d_dot", "0074.wav", ":d."); 

		// phrase: std_e_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_e_dot", "0075.wav", ":e."); 

		// phrase: std_f_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_f_dot", "0076.wav", ":f."); 

		// phrase: std_g_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_g_dot", "0077.wav", ":g."); 

		// phrase: std_h_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_h_dot", "0078.wav", ":h."); 

		// phrase: std_i_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_i_dot", "0079.wav", ":i."); 

		// phrase: std_j_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_j_dot", "0080.wav", ":j."); 

		// phrase: std_k_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_k_dot", "0081.wav", ":k."); 

		// phrase: std_l_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_l_dot", "0082.wav", ":l."); 

		// phrase: std_m_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_m_dot", "0083.wav", ":m."); 

		// phrase: std_n_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_n_dot", "0084.wav", ":n."); 

		// phrase: std_o_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_o_dot", "0085.wav", ":o."); 

		// phrase: std_p_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_p_dot", "0086.wav", ":p."); 

		// phrase: std_q_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_q_dot", "0087.wav", ":q."); 

		// phrase: std_r_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_r_dot", "0088.wav", ":r."); 

		// phrase: std_s_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_s_dot", "0089.wav", ":s."); 

		// phrase: std_t_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_t_dot", "0090.wav", ":t."); 

		// phrase: std_u_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_u_dot", "0091.wav", ":u."); 

		// phrase: std_v_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_v_dot", "0092.wav", ":v."); 

		// phrase: std_w_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_w_dot", "0093.wav", ":w."); 

		// phrase: std_x_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_x_dot", "0094.wav", ":x."); 

		// phrase: std_y_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_y_dot", "0095.wav", ":y."); 

		// phrase: std_z_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_z_dot", "0096.wav", ":z."); 

		// phrase: std_0_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_0_dot", "0100.wav", ":0."); 

		// phrase: std_1_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_1_dot", "0101.wav", ":1."); 

		// phrase: std_2_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_2_dot", "0102.wav", ":2."); 

		// phrase: std_3_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_3_dot", "0103.wav", ":3."); 

		// phrase: std_4_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_4_dot", "0104.wav", ":4."); 

		// phrase: std_5_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_5_dot", "0105.wav", ":5."); 

		// phrase: std_6_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_6_dot", "0106.wav", ":6."); 

		// phrase: std_7_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_7_dot", "0107.wav", ":7."); 

		// phrase: std_8_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_8_dot", "0108.wav", ":8."); 

		// phrase: std_9_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_9_dot", "0109.wav", ":9."); 

		// phrase: std_10_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_10_dot", "0110.wav", ":10."); 

		// phrase: std_11_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_11_dot", "0111.wav", ":11."); 

		// phrase: std_12_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_12_dot", "0112.wav", ":12."); 

		// phrase: std_13_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_13_dot", "0113.wav", ":13."); 

		// phrase: std_14_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_14_dot", "0114.wav", ":14."); 

		// phrase: std_15_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_15_dot", "0115.wav", ":15."); 

		// phrase: std_16_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_16_dot", "0116.wav", ":16."); 

		// phrase: std_17_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_17_dot", "0117.wav", ":17."); 

		// phrase: std_18_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_18_dot", "0118.wav", ":18."); 

		// phrase: std_19_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_19_dot", "0119.wav", ":19."); 

		// phrase: std_20_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_20_dot", "0120.wav", ":20."); 

		// phrase: std_30_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_30_dot", "0121.wav", ":30."); 

		// phrase: std_40_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_40_dot", "0122.wav", ":40."); 

		// phrase: std_50_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_50_dot", "0123.wav", ":50."); 

		// phrase: std_60_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_60_dot", "0124.wav", ":60."); 

		// phrase: std_70_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_70_dot", "0125.wav", ":70."); 

		// phrase: std_80_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_80_dot", "0126.wav", ":80."); 

		// phrase: std_90_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_90_dot", "0127.wav", ":90."); 

		// phrase: std_100_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_100_dot", "0128.wav", ":100."); 

		// phrase: std_200_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_200_dot", "0129.wav", ":200."); 

		// phrase: std_300_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_300_dot", "0130.wav", ":300."); 

		// phrase: std_400_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_400_dot", "0131.wav", ":400."); 

		// phrase: std_500_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_500_dot", "0132.wav", ":500."); 

		// phrase: std_600_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_600_dot", "0133.wav", ":600."); 

		// phrase: std_700_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_700_dot", "0134.wav", ":700."); 

		// phrase: std_800_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_800_dot", "0135.wav", ":800."); 

		// phrase: std_900_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_900_dot", "0136.wav", ":900."); 

		// phrase: std_a_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_a_q", "0141.wav", ":a?"); 

		// phrase: std_b_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_b_q", "0142.wav", ":b?"); 

		// phrase: std_c_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_c_q", "0143.wav", ":c?"); 

		// phrase: std_d_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_d_q", "0144.wav", ":d?"); 

		// phrase: std_e_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_e_q", "0145.wav", ":e?"); 

		// phrase: std_f_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_f_q", "0146.wav", ":f?"); 

		// phrase: std_g_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_g_q", "0147.wav", ":g?"); 

		// phrase: std_h_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_h_q", "0148.wav", ":h?"); 

		// phrase: std_i_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_i_q", "0149.wav", ":i?"); 

		// phrase: std_j_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_j_q", "0150.wav", ":j?"); 

		// phrase: std_k_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_k_q", "0151.wav", ":k?"); 

		// phrase: std_l_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_l_q", "0152.wav", ":l?"); 

		// phrase: std_m_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_m_q", "0153.wav", ":m?"); 

		// phrase: std_n_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_n_q", "0154.wav", ":n?"); 

		// phrase: std_o_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_o_q", "0155.wav", ":o?"); 

		// phrase: std_p_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_p_q", "0156.wav", ":p?"); 

		// phrase: std_q_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_q_q", "0157.wav", ":q?"); 

		// phrase: std_r_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_r_q", "0158.wav", ":r?"); 

		// phrase: std_s_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_s_q", "0159.wav", ":s?"); 

		// phrase: std_t_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_t_q", "0160.wav", ":t?"); 

		// phrase: std_u_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_u_q", "0161.wav", ":u?"); 

		// phrase: std_v_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_v_q", "0162.wav", ":v?"); 

		// phrase: std_w_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_w_q", "0163.wav", ":w?"); 

		// phrase: std_x_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_x_q", "0164.wav", ":x?"); 

		// phrase: std_y_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_y_q", "0165.wav", ":y?"); 

		// phrase: std_z_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_z_q", "0166.wav", ":z?"); 

		// phrase: std_0_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_0_q", "0170.wav", ":0?"); 

		// phrase: std_1_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_1_q", "0171.wav", ":1?"); 

		// phrase: std_2_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_2_q", "0172.wav", ":2?"); 

		// phrase: std_3_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_3_q", "0173.wav", ":3?"); 

		// phrase: std_4_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_4_q", "0174.wav", ":4?"); 

		// phrase: std_5_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_5_q", "0175.wav", ":5?"); 

		// phrase: std_6_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_6_q", "0176.wav", ":6?"); 

		// phrase: std_7_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_7_q", "0177.wav", ":7?"); 

		// phrase: std_8_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_8_q", "0178.wav", ":8?"); 

		// phrase: std_9_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_9_q", "0179.wav", ":9?"); 

		// phrase: std_10_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_10_q", "0180.wav", ":10?"); 

		// phrase: std_11_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_11_q", "0181.wav", ":11?"); 

		// phrase: std_12_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_12_q", "0182.wav", ":12?"); 

		// phrase: std_13_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_13_q", "0183.wav", ":13?"); 

		// phrase: std_14_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_14_q", "0184.wav", ":14?"); 

		// phrase: std_15_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_15_q", "0185.wav", ":15?"); 

		// phrase: std_16_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_16_q", "0186.wav", ":16?"); 

		// phrase: std_17_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_17_q", "0187.wav", ":17?"); 

		// phrase: std_18_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_18_q", "0188.wav", ":18?"); 

		// phrase: std_19_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_19_q", "0189.wav", ":19?"); 

		// phrase: std_20_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_20_q", "0190.wav", ":20?"); 

		// phrase: std_30_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_30_q", "0191.wav", ":30?"); 

		// phrase: std_40_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_40_q", "0192.wav", ":40?"); 

		// phrase: std_50_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_50_q", "0193.wav", ":50?"); 

		// phrase: std_60_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_60_q", "0194.wav", ":60?"); 

		// phrase: std_70_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_70_q", "0195.wav", ":70?"); 

		// phrase: std_80_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_80_q", "0196.wav", ":80?"); 

		// phrase: std_90_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_90_q", "0197.wav", ":90?"); 

		// phrase: std_100_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_100_q", "0198.wav", ":100?"); 

		// phrase: std_200_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_200_q", "0199.wav", ":200?"); 

		// phrase: std_300_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_300_q", "0200.wav", ":300?"); 

		// phrase: std_400_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_400_q", "0201.wav", ":400?"); 

		// phrase: std_500_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_500_q", "0202.wav", ":500?"); 

		// phrase: std_600_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_600_q", "0203.wav", ":600?"); 

		// phrase: std_700_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_700_q", "0204.wav", ":700?"); 

		// phrase: std_800_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_800_q", "0205.wav", ":800?"); 

		// phrase: std_900_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_900_q", "0206.wav", ":900?"); 

		// phrase: std_janeiro
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_janeiro", "0210.wav", ":janeiro"); 

		// phrase: std_fevereiro
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_fevereiro", "0211.wav", ":fevereiro"); 

		// phrase: std_marco
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_marco", "0212.wav", ":marco"); 

		// phrase: std_abril
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_abril", "0213.wav", ":abril"); 

		// phrase: std_maio
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_maio", "0214.wav", ":maio"); 

		// phrase: std_junho
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_junho", "0215.wav", ":junho"); 

		// phrase: std_julho
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_julho", "0216.wav", ":julho"); 

		// phrase: std_agosto
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_agosto", "0217.wav", ":agosto"); 

		// phrase: std_setembro
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_setembro", "0218.wav", ":setembro"); 

		// phrase: std_outubro
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_outubro", "0219.wav", ":outubro"); 

		// phrase: std_novembro
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_novembro", "0220.wav", ":novembro"); 

		// phrase: std_dezembro
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_dezembro", "0221.wav", ":dezembro"); 

		// phrase: std_domingo
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_domingo", "0230.wav", ":domingo"); 

		// phrase: std_segunda_dash_feira
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_segunda_dash_feira", "0231.wav", ":segunda-feira"); 

		// phrase: std_terca_dash_feira
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_terca_dash_feira", "0232.wav", ":terca-feira"); 

		// phrase: std_quarta_dash_feira
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_quarta_dash_feira", "0233.wav", ":quarta-feira"); 

		// phrase: std_quinta_dash_feira
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_quinta_dash_feira", "0234.wav", ":quinta-feira"); 

		// phrase: std_sexta_dash_feira
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_sexta_dash_feira", "0235.wav", ":sexta-feira"); 

		// phrase: std_sabado
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_sabado", "0236.wav", ":sabado"); 

		// phrase: std_primeiro
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_primeiro", "0240.wav", ":primeiro"); 

		// phrase: std_1_lparen_fem_rparen
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_1_lparen_fem_rparen", "0241.wav", ":1(fem)"); 

		// phrase: std_2_lparen_fem_rparen
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_2_lparen_fem_rparen", "0242.wav", ":2(fem)"); 

		// phrase: std_200_lparen_fem_rparen
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_200_lparen_fem_rparen", "0259.wav", ":200(fem)"); 

		// phrase: std_300_lparen_fem_rparen
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_300_lparen_fem_rparen", "0260.wav", ":300(fem)"); 

		// phrase: std_400_lparen_fem_rparen
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_400_lparen_fem_rparen", "0261.wav", ":400(fem)"); 

		// phrase: std_500_lparen_fem_rparen
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_500_lparen_fem_rparen", "0262.wav", ":500(fem)"); 

		// phrase: std_600_lparen_fem_rparen
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_600_lparen_fem_rparen", "0263.wav", ":600(fem)"); 

		// phrase: std_700_lparen_fem_rparen
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_700_lparen_fem_rparen", "0264.wav", ":700(fem)"); 

		// phrase: std_800_lparen_fem_rparen
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_800_lparen_fem_rparen", "0265.wav", ":800(fem)"); 

		// phrase: std_900_lparen_fem_rparen
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_900_lparen_fem_rparen", "0266.wav", ":900(fem)"); 

		// phrase: std_plus_1_lparen_fem_rparen
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_1_lparen_fem_rparen", "0267.wav", ":+1(fem)"); 

		// phrase: std_plus_2_lparen_fem_rparen
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_2_lparen_fem_rparen", "0268.wav", ":+2(fem)"); 

		// phrase: std_plus_200_lparen_fem_rparen
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_200_lparen_fem_rparen", "0285.wav", ":+200(fem)"); 

		// phrase: std_plus_300_lparen_fem_rparen
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_300_lparen_fem_rparen", "0286.wav", ":+300(fem)"); 

		// phrase: std_plus_400_lparen_fem_rparen
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_400_lparen_fem_rparen", "0287.wav", ":+400(fem)"); 

		// phrase: std_plus_500_lparen_fem_rparen
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_500_lparen_fem_rparen", "0288.wav", ":+500(fem)"); 

		// phrase: std_plus_600_lparen_fem_rparen
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_600_lparen_fem_rparen", "0289.wav", ":+600(fem)"); 

		// phrase: std_plus_700_lparen_fem_rparen
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_700_lparen_fem_rparen", "0290.wav", ":+700(fem)"); 

		// phrase: std_plus_800_lparen_fem_rparen
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_800_lparen_fem_rparen", "0291.wav", ":+800(fem)"); 

		// phrase: std_plus_900_lparen_fem_rparen
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_900_lparen_fem_rparen", "0292.wav", ":+900(fem)"); 

		// phrase: std_plus_0
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_0", "0300.wav", ":+0"); 

		// phrase: std_plus_1
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_1", "0301.wav", ":+1"); 

		// phrase: std_plus_2
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_2", "0302.wav", ":+2"); 

		// phrase: std_plus_3
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_3", "0303.wav", ":+3"); 

		// phrase: std_plus_4
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_4", "0304.wav", ":+4"); 

		// phrase: std_plus_5
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_5", "0305.wav", ":+5"); 

		// phrase: std_plus_6
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_6", "0306.wav", ":+6"); 

		// phrase: std_plus_7
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_7", "0307.wav", ":+7"); 

		// phrase: std_plus_8
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_8", "0308.wav", ":+8"); 

		// phrase: std_plus_9
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_9", "0309.wav", ":+9"); 

		// phrase: std_plus_10
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_10", "0310.wav", ":+10"); 

		// phrase: std_plus_11
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_11", "0311.wav", ":+11"); 

		// phrase: std_plus_12
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_12", "0312.wav", ":+12"); 

		// phrase: std_plus_13
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_13", "0313.wav", ":+13"); 

		// phrase: std_plus_14
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_14", "0314.wav", ":+14"); 

		// phrase: std_plus_15
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_15", "0315.wav", ":+15"); 

		// phrase: std_plus_16
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_16", "0316.wav", ":+16"); 

		// phrase: std_plus_17
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_17", "0317.wav", ":+17"); 

		// phrase: std_plus_18
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_18", "0318.wav", ":+18"); 

		// phrase: std_plus_19
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_19", "0319.wav", ":+19"); 

		// phrase: std_plus_20
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_20", "0320.wav", ":+20"); 

		// phrase: std_plus_30
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_30", "0321.wav", ":+30"); 

		// phrase: std_plus_40
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_40", "0322.wav", ":+40"); 

		// phrase: std_plus_50
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_50", "0323.wav", ":+50"); 

		// phrase: std_plus_60
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_60", "0324.wav", ":+60"); 

		// phrase: std_plus_70
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_70", "0325.wav", ":+70"); 

		// phrase: std_plus_80
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_80", "0326.wav", ":+80"); 

		// phrase: std_plus_90
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_90", "0327.wav", ":+90"); 

		// phrase: std_plus_100
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_100", "0328.wav", ":+100"); 

		// phrase: std_plus_200
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_200", "0329.wav", ":+200"); 

		// phrase: std_plus_300
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_300", "0330.wav", ":+300"); 

		// phrase: std_plus_400
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_400", "0331.wav", ":+400"); 

		// phrase: std_plus_500
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_500", "0332.wav", ":+500"); 

		// phrase: std_plus_600
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_600", "0333.wav", ":+600"); 

		// phrase: std_plus_700
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_700", "0334.wav", ":+700"); 

		// phrase: std_plus_800
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_800", "0335.wav", ":+800"); 

		// phrase: std_plus_900
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_900", "0336.wav", ":+900"); 

		// phrase: std_plus_100_plus
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_100_plus", "0337.wav", ":+100+"); 

		// phrase: std_real
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_real", "0340.wav", ":real"); 

		// phrase: std_reais
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_reais", "0341.wav", ":reais"); 

		// phrase: std_centavo
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_centavo", "0342.wav", ":centavo"); 

		// phrase: std_centavos
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_centavos", "0343.wav", ":centavos"); 

		// phrase: std_mil
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_mil", "0344.wav", ":mil"); 

		// phrase: std_milhao
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_milhao", "0345.wav", ":milhao"); 

		// phrase: std_milhoes
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_milhoes", "0346.wav", ":milhoes"); 

		// phrase: std_bilhao
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_bilhao", "0347.wav", ":bilhao"); 

		// phrase: std_bilhoes
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_bilhoes", "0348.wav", ":bilhoes"); 

		// phrase: std_trilhao
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_trilhao", "0349.wav", ":trilhao"); 

		// phrase: std_trilhoes
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_trilhoes", "0350.wav", ":trilhoes"); 

		// phrase: std_hora
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_hora", "0360.wav", ":hora"); 

		// phrase: std_horas
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_horas", "0361.wav", ":horas"); 

		// phrase: std_minuto
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_minuto", "0362.wav", ":minuto"); 

		// phrase: std_minutos
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_minutos", "0363.wav", ":minutos"); 

		// phrase: std_da_manha
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_da_manha", "0364.wav", ":da manha"); 

		// phrase: std_da_tarde
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_da_tarde", "0365.wav", ":da tarde"); 

		// phrase: std_da_noite
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_da_noite", "0366.wav", ":da noite"); 

		// phrase: std_e_meia
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_e_meia", "0367.wav", ":e meia"); 

		// phrase: std_meiodia
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_meiodia", "0368.wav", ":meiodia"); 

		// phrase: std_maianoite
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_maianoite", "0369.wav", ":maianoite"); 

		// phrase: std_negativo
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_negativo", "0370.wav", ":negativo"); 

		// phrase: std_virgula
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_virgula", "0371.wav", ":virgula"); 

		// phrase: std_de
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_de", "0372.wav", ":de"); 

		// phrase: std_and
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_and", "0373.wav", ":e"); 

		// phrase: std_janeiro_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_janeiro_dot", "0460.wav", ":janeiro."); 

		// phrase: std_fevereiro_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_fevereiro_dot", "0461.wav", ":fevereiro."); 

		// phrase: std_marco_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_marco_dot", "0462.wav", ":marco."); 

		// phrase: std_abril_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_abril_dot", "0463.wav", ":abril."); 

		// phrase: std_maio_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_maio_dot", "0464.wav", ":maio."); 

		// phrase: std_junho_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_junho_dot", "0465.wav", ":junho."); 

		// phrase: std_julho_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_julho_dot", "0466.wav", ":julho."); 

		// phrase: std_agosto_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_agosto_dot", "0467.wav", ":agosto."); 

		// phrase: std_setembro_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_setembro_dot", "0468.wav", ":setembro."); 

		// phrase: std_outubro_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_outubro_dot", "0469.wav", ":outubro."); 

		// phrase: std_novembro_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_novembro_dot", "0470.wav", ":novembro."); 

		// phrase: std_dezembro_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_dezembro_dot", "0471.wav", ":dezembro."); 

		// phrase: std_domingo_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_domingo_dot", "0480.wav", ":domingo."); 

		// phrase: std_segunda_dash_feira_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_segunda_dash_feira_dot", "0481.wav", ":segunda-feira."); 

		// phrase: std_terca_dash_feira_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_terca_dash_feira_dot", "0482.wav", ":terca-feira."); 

		// phrase: std_quarta_dash_feira_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_quarta_dash_feira_dot", "0483.wav", ":quarta-feira."); 

		// phrase: std_quinta_dash_feira_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_quinta_dash_feira_dot", "0484.wav", ":quinta-feira."); 

		// phrase: std_sexta_dash_feira_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_sexta_dash_feira_dot", "0485.wav", ":sexta-feira."); 

		// phrase: std_sabado_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_sabado_dot", "0486.wav", ":sabado."); 

		// phrase: std_primeiro_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_primeiro_dot", "0490.wav", ":primeiro."); 

		// phrase: std_1_lparen_fem_rparen_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_1_lparen_fem_rparen_dot", "0491.wav", ":1(fem)."); 

		// phrase: std_2_lparen_fem_rparen_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_2_lparen_fem_rparen_dot", "0492.wav", ":2(fem)."); 

		// phrase: std_200_lparen_fem_rparen_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_200_lparen_fem_rparen_dot", "0509.wav", ":200(fem)."); 

		// phrase: std_300_lparen_fem_rparen_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_300_lparen_fem_rparen_dot", "0510.wav", ":300(fem)."); 

		// phrase: std_400_lparen_fem_rparen_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_400_lparen_fem_rparen_dot", "0511.wav", ":400(fem)."); 

		// phrase: std_500_lparen_fem_rparen_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_500_lparen_fem_rparen_dot", "0512.wav", ":500(fem)."); 

		// phrase: std_600_lparen_fem_rparen_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_600_lparen_fem_rparen_dot", "0513.wav", ":600(fem)."); 

		// phrase: std_700_lparen_fem_rparen_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_700_lparen_fem_rparen_dot", "0514.wav", ":700(fem)."); 

		// phrase: std_800_lparen_fem_rparen_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_800_lparen_fem_rparen_dot", "0515.wav", ":800(fem)."); 

		// phrase: std_900_lparen_fem_rparen_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_900_lparen_fem_rparen_dot", "0516.wav", ":900(fem)."); 

		// phrase: std_plus_1_lparen_fem_rparen_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_1_lparen_fem_rparen_dot", "0517.wav", ":+1(fem)."); 

		// phrase: std_plus_2_lparen_fem_rparen_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_2_lparen_fem_rparen_dot", "0518.wav", ":+2(fem)."); 

		// phrase: std_plus_200_lparen_fem_rparen_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_200_lparen_fem_rparen_dot", "0535.wav", ":+200(fem)."); 

		// phrase: std_plus_300_lparen_fem_rparen_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_300_lparen_fem_rparen_dot", "0536.wav", ":+300(fem)."); 

		// phrase: std_plus_400_lparen_fem_rparen_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_400_lparen_fem_rparen_dot", "0537.wav", ":+400(fem)."); 

		// phrase: std_plus_500_lparen_fem_rparen_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_500_lparen_fem_rparen_dot", "0538.wav", ":+500(fem)."); 

		// phrase: std_plus_600_lparen_fem_rparen_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_600_lparen_fem_rparen_dot", "0539.wav", ":+600(fem)."); 

		// phrase: std_plus_700_lparen_fem_rparen_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_700_lparen_fem_rparen_dot", "0540.wav", ":+700(fem)."); 

		// phrase: std_plus_800_lparen_fem_rparen_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_800_lparen_fem_rparen_dot", "0541.wav", ":+800(fem)."); 

		// phrase: std_plus_900_lparen_fem_rparen_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_900_lparen_fem_rparen_dot", "0542.wav", ":+900(fem)."); 

		// phrase: std_plus_0_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_0_dot", "0550.wav", ":+0."); 

		// phrase: std_plus_1_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_1_dot", "0551.wav", ":+1."); 

		// phrase: std_plus_2_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_2_dot", "0552.wav", ":+2."); 

		// phrase: std_plus_3_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_3_dot", "0553.wav", ":+3."); 

		// phrase: std_plus_4_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_4_dot", "0554.wav", ":+4."); 

		// phrase: std_plus_5_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_5_dot", "0555.wav", ":+5."); 

		// phrase: std_plus_6_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_6_dot", "0556.wav", ":+6."); 

		// phrase: std_plus_7_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_7_dot", "0557.wav", ":+7."); 

		// phrase: std_plus_8_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_8_dot", "0558.wav", ":+8."); 

		// phrase: std_plus_9_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_9_dot", "0559.wav", ":+9."); 

		// phrase: std_plus_10_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_10_dot", "0560.wav", ":+10."); 

		// phrase: std_plus_11_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_11_dot", "0561.wav", ":+11."); 

		// phrase: std_plus_12_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_12_dot", "0562.wav", ":+12."); 

		// phrase: std_plus_13_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_13_dot", "0563.wav", ":+13."); 

		// phrase: std_plus_14_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_14_dot", "0564.wav", ":+14."); 

		// phrase: std_plus_15_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_15_dot", "0565.wav", ":+15."); 

		// phrase: std_plus_16_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_16_dot", "0566.wav", ":+16."); 

		// phrase: std_plus_17_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_17_dot", "0567.wav", ":+17."); 

		// phrase: std_plus_18_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_18_dot", "0568.wav", ":+18."); 

		// phrase: std_plus_19_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_19_dot", "0569.wav", ":+19."); 

		// phrase: std_plus_20_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_20_dot", "0570.wav", ":+20."); 

		// phrase: std_plus_30_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_30_dot", "0571.wav", ":+30."); 

		// phrase: std_plus_40_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_40_dot", "0572.wav", ":+40."); 

		// phrase: std_plus_50_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_50_dot", "0573.wav", ":+50."); 

		// phrase: std_plus_60_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_60_dot", "0574.wav", ":+60."); 

		// phrase: std_plus_70_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_70_dot", "0575.wav", ":+70."); 

		// phrase: std_plus_80_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_80_dot", "0576.wav", ":+80."); 

		// phrase: std_plus_90_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_90_dot", "0577.wav", ":+90."); 

		// phrase: std_plus_100_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_100_dot", "0578.wav", ":+100."); 

		// phrase: std_plus_200_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_200_dot", "0579.wav", ":+200."); 

		// phrase: std_plus_300_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_300_dot", "0580.wav", ":+300."); 

		// phrase: std_plus_400_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_400_dot", "0581.wav", ":+400."); 

		// phrase: std_plus_500_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_500_dot", "0582.wav", ":+500."); 

		// phrase: std_plus_600_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_600_dot", "0583.wav", ":+600."); 

		// phrase: std_plus_700_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_700_dot", "0584.wav", ":+700."); 

		// phrase: std_plus_800_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_800_dot", "0585.wav", ":+800."); 

		// phrase: std_plus_900_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_900_dot", "0586.wav", ":+900."); 

		// phrase: std_real_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_real_dot", "0590.wav", ":real."); 

		// phrase: std_reais_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_reais_dot", "0591.wav", ":reais."); 

		// phrase: std_centavo_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_centavo_dot", "0592.wav", ":centavo."); 

		// phrase: std_centavos_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_centavos_dot", "0593.wav", ":centavos."); 

		// phrase: std_mil_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_mil_dot", "0594.wav", ":mil."); 

		// phrase: std_milhao_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_milhao_dot", "0595.wav", ":milhao."); 

		// phrase: std_milhoes_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_milhoes_dot", "0596.wav", ":milhoes."); 

		// phrase: std_bilhao_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_bilhao_dot", "0597.wav", ":bilhao."); 

		// phrase: std_bilhoes_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_bilhoes_dot", "0598.wav", ":bilhoes."); 

		// phrase: std_trilhao_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_trilhao_dot", "0599.wav", ":trilhao."); 

		// phrase: std_trilhoes_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_trilhoes_dot", "0600.wav", ":trilhoes."); 

		// phrase: std_hora_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_hora_dot", "0610.wav", ":hora."); 

		// phrase: std_horas_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_horas_dot", "0611.wav", ":horas."); 

		// phrase: std_minuto_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_minuto_dot", "0612.wav", ":minuto."); 

		// phrase: std_minutos_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_minutos_dot", "0613.wav", ":minutos."); 

		// phrase: std_da_manha_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_da_manha_dot", "0614.wav", ":da manha."); 

		// phrase: std_da_tarde_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_da_tarde_dot", "0615.wav", ":da tarde."); 

		// phrase: std_da_noite_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_da_noite_dot", "0616.wav", ":da noite."); 

		// phrase: std_e_meia_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_e_meia_dot", "0617.wav", ":e meia."); 

		// phrase: std_meiodia_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_meiodia_dot", "0618.wav", ":meiodia."); 

		// phrase: std_maianoite_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_maianoite_dot", "0619.wav", ":maianoite."); 

		// phrase: std_negativo_dot
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_negativo_dot", "0620.wav", ":negativo."); 

		// phrase: std_janeiro_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_janeiro_q", "0710.wav", ":janeiro?"); 

		// phrase: std_fevereiro_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_fevereiro_q", "0711.wav", ":fevereiro?"); 

		// phrase: std_marco_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_marco_q", "0712.wav", ":marco?"); 

		// phrase: std_abril_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_abril_q", "0713.wav", ":abril?"); 

		// phrase: std_maio_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_maio_q", "0714.wav", ":maio?"); 

		// phrase: std_junho_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_junho_q", "0715.wav", ":junho?"); 

		// phrase: std_julho_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_julho_q", "0716.wav", ":julho?"); 

		// phrase: std_agosto_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_agosto_q", "0717.wav", ":agosto?"); 

		// phrase: std_setembro_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_setembro_q", "0718.wav", ":setembro?"); 

		// phrase: std_outubro_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_outubro_q", "0719.wav", ":outubro?"); 

		// phrase: std_novembro_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_novembro_q", "0720.wav", ":novembro?"); 

		// phrase: std_dezembro_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_dezembro_q", "0721.wav", ":dezembro?"); 

		// phrase: std_domingo_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_domingo_q", "0730.wav", ":domingo?"); 

		// phrase: std_segunda_dash_feira_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_segunda_dash_feira_q", "0731.wav", ":segunda-feira?"); 

		// phrase: std_terca_dash_feira_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_terca_dash_feira_q", "0732.wav", ":terca-feira?"); 

		// phrase: std_quarta_dash_feira_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_quarta_dash_feira_q", "0733.wav", ":quarta-feira?"); 

		// phrase: std_quinta_dash_feira_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_quinta_dash_feira_q", "0734.wav", ":quinta-feira?"); 

		// phrase: std_sexta_dash_feira_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_sexta_dash_feira_q", "0735.wav", ":sexta-feira?"); 

		// phrase: std_sabado_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_sabado_q", "0736.wav", ":sabado?"); 

		// phrase: std_primeiro_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_primeiro_q", "0740.wav", ":primeiro?"); 

		// phrase: std_1_lparen_fem_rparen_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_1_lparen_fem_rparen_q", "0741.wav", ":1(fem)?"); 

		// phrase: std_2_lparen_fem_rparen_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_2_lparen_fem_rparen_q", "0742.wav", ":2(fem)?"); 

		// phrase: std_200_lparen_fem_rparen_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_200_lparen_fem_rparen_q", "0759.wav", ":200(fem)?"); 

		// phrase: std_300_lparen_fem_rparen_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_300_lparen_fem_rparen_q", "0760.wav", ":300(fem)?"); 

		// phrase: std_400_lparen_fem_rparen_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_400_lparen_fem_rparen_q", "0761.wav", ":400(fem)?"); 

		// phrase: std_500_lparen_fem_rparen_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_500_lparen_fem_rparen_q", "0762.wav", ":500(fem)?"); 

		// phrase: std_600_lparen_fem_rparen_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_600_lparen_fem_rparen_q", "0763.wav", ":600(fem)?"); 

		// phrase: std_700_lparen_fem_rparen_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_700_lparen_fem_rparen_q", "0764.wav", ":700(fem)?"); 

		// phrase: std_800_lparen_fem_rparen_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_800_lparen_fem_rparen_q", "0765.wav", ":800(fem)?"); 

		// phrase: std_900_lparen_fem_rparen_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_900_lparen_fem_rparen_q", "0766.wav", ":900(fem)?"); 

		// phrase: std_plus_1_lparen_fem_rparen_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_1_lparen_fem_rparen_q", "0767.wav", ":+1(fem)?"); 

		// phrase: std_plus_2_lparen_fem_rparen_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_2_lparen_fem_rparen_q", "0768.wav", ":+2(fem)?"); 

		// phrase: std_plus_200_lparen_fem_rparen_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_200_lparen_fem_rparen_q", "0785.wav", ":+200(fem)?"); 

		// phrase: std_plus_300_lparen_fem_rparen_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_300_lparen_fem_rparen_q", "0786.wav", ":+300(fem)?"); 

		// phrase: std_plus_400_lparen_fem_rparen_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_400_lparen_fem_rparen_q", "0787.wav", ":+400(fem)?"); 

		// phrase: std_plus_500_lparen_fem_rparen_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_500_lparen_fem_rparen_q", "0788.wav", ":+500(fem)?"); 

		// phrase: std_plus_600_lparen_fem_rparen_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_600_lparen_fem_rparen_q", "0789.wav", ":+600(fem)?"); 

		// phrase: std_plus_700_lparen_fem_rparen_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_700_lparen_fem_rparen_q", "0790.wav", ":+700(fem)?"); 

		// phrase: std_plus_800_lparen_fem_rparen_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_800_lparen_fem_rparen_q", "0791.wav", ":+800(fem)?"); 

		// phrase: std_plus_900_lparen_fem_rparen_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_900_lparen_fem_rparen_q", "0792.wav", ":+900(fem)?"); 

		// phrase: std_plus_0_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_0_q", "0800.wav", ":+0?"); 

		// phrase: std_plus_1_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_1_q", "0801.wav", ":+1?"); 

		// phrase: std_plus_2_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_2_q", "0802.wav", ":+2?"); 

		// phrase: std_plus_3_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_3_q", "0803.wav", ":+3?"); 

		// phrase: std_plus_4_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_4_q", "0804.wav", ":+4?"); 

		// phrase: std_plus_5_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_5_q", "0805.wav", ":+5?"); 

		// phrase: std_plus_6_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_6_q", "0806.wav", ":+6?"); 

		// phrase: std_plus_7_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_7_q", "0807.wav", ":+7?"); 

		// phrase: std_plus_8_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_8_q", "0808.wav", ":+8?"); 

		// phrase: std_plus_9_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_9_q", "0809.wav", ":+9?"); 

		// phrase: std_plus_10_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_10_q", "0810.wav", ":+10?"); 

		// phrase: std_plus_11_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_11_q", "0811.wav", ":+11?"); 

		// phrase: std_plus_12_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_12_q", "0812.wav", ":+12?"); 

		// phrase: std_plus_13_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_13_q", "0813.wav", ":+13?"); 

		// phrase: std_plus_14_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_14_q", "0814.wav", ":+14?"); 

		// phrase: std_plus_15_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_15_q", "0815.wav", ":+15?"); 

		// phrase: std_plus_16_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_16_q", "0816.wav", ":+16?"); 

		// phrase: std_plus_17_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_17_q", "0817.wav", ":+17?"); 

		// phrase: std_plus_18_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_18_q", "0818.wav", ":+18?"); 

		// phrase: std_plus_19_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_19_q", "0819.wav", ":+19?"); 

		// phrase: std_plus_20_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_20_q", "0820.wav", ":+20?"); 

		// phrase: std_plus_30_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_30_q", "0821.wav", ":+30?"); 

		// phrase: std_plus_40_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_40_q", "0822.wav", ":+40?"); 

		// phrase: std_plus_50_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_50_q", "0823.wav", ":+50?"); 

		// phrase: std_plus_60_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_60_q", "0824.wav", ":+60?"); 

		// phrase: std_plus_70_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_70_q", "0825.wav", ":+70?"); 

		// phrase: std_plus_80_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_80_q", "0826.wav", ":+80?"); 

		// phrase: std_plus_90_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_90_q", "0827.wav", ":+90?"); 

		// phrase: std_plus_100_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_100_q", "0828.wav", ":+100?"); 

		// phrase: std_plus_200_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_200_q", "0829.wav", ":+200?"); 

		// phrase: std_plus_300_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_300_q", "0830.wav", ":+300?"); 

		// phrase: std_plus_400_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_400_q", "0831.wav", ":+400?"); 

		// phrase: std_plus_500_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_500_q", "0832.wav", ":+500?"); 

		// phrase: std_plus_600_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_600_q", "0833.wav", ":+600?"); 

		// phrase: std_plus_700_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_700_q", "0834.wav", ":+700?"); 

		// phrase: std_plus_800_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_800_q", "0835.wav", ":+800?"); 

		// phrase: std_plus_900_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_plus_900_q", "0836.wav", ":+900?"); 

		// phrase: std_real_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_real_q", "0840.wav", ":real?"); 

		// phrase: std_reais_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_reais_q", "0841.wav", ":reais?"); 

		// phrase: std_centavo_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_centavo_q", "0842.wav", ":centavo?"); 

		// phrase: std_centavos_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_centavos_q", "0843.wav", ":centavos?"); 

		// phrase: std_mil_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_mil_q", "0844.wav", ":mil?"); 

		// phrase: std_milhao_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_milhao_q", "0845.wav", ":milhao?"); 

		// phrase: std_milhoes_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_milhoes_q", "0846.wav", ":milhoes?"); 

		// phrase: std_bilhao_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_bilhao_q", "0847.wav", ":bilhao?"); 

		// phrase: std_bilhoes_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_bilhoes_q", "0848.wav", ":bilhoes?"); 

		// phrase: std_trilhao_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_trilhao_q", "0849.wav", ":trilhao?"); 

		// phrase: std_trilhoes_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_trilhoes_q", "0850.wav", ":trilhoes?"); 

		// phrase: std_hora_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_hora_q", "0860.wav", ":hora?"); 

		// phrase: std_horas_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_horas_q", "0861.wav", ":horas?"); 

		// phrase: std_minuto_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_minuto_q", "0862.wav", ":minuto?"); 

		// phrase: std_minutos_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_minutos_q", "0863.wav", ":minutos?"); 

		// phrase: std_da_manha_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_da_manha_q", "0864.wav", ":da manha?"); 

		// phrase: std_da_tarde_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_da_tarde_q", "0865.wav", ":da tarde?"); 

		// phrase: std_da_noite_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_da_noite_q", "0866.wav", ":da noite?"); 

		// phrase: std_e_meia_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_e_meia_q", "0867.wav", ":e meia?"); 

		// phrase: std_meiodia_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_meiodia_q", "0868.wav", ":meiodia?"); 

		// phrase: std_maianoite_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_maianoite_q", "0869.wav", ":maianoite?"); 

		// phrase: std_negativo_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_negativo_q", "0870.wav", ":negativo?"); 

		// phrase: std_sil_dot_050
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_sil_dot_050", "0880.wav", ":sil.050"); 

		// phrase: std_sil_dot_100
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_sil_dot_100", "0881.wav", ":sil.100"); 

		// phrase: std_sil_dot_200
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_sil_dot_200", "0882.wav", ":sil.200"); 

		// phrase: std_sil_dot_300
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_sil_dot_300", "0883.wav", ":sil.300"); 

		// phrase: std_sil_dot_400
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_sil_dot_400", "0884.wav", ":sil.400"); 

		// phrase: std_sil_dot_500
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_sil_dot_500", "0885.wav", ":sil.500"); 

		// phrase: std_sil_dot_600
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_sil_dot_600", "0886.wav", ":sil.600"); 

		//}}END:PHRASESET:STATIC
	}
	/**
	 * Returns the Phrase with the given name.  To override the
	 * behavior and dynamically return a different Phrase object,
	 * override the method "hookGetPhrase(...)".
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 20 DE ABRIL DE 2016 9H24MIN53S BRT
	 * @see com.avaya.sce.runtime.Phraseset#getPhrase(String) 
	 */ 
	public com.avaya.sce.runtime.Phrase getPhrase(String phraseName) {
		return(getPhrase(std_pt_br.PHRASE_MAP, phraseName));
	}
}
