package flow.subflow.ValidacaoMultiplus;

/**
 * This servlet is the exit point of a subflow.  The base class handles
 * the logic for forwarding to the next servlet.
 * Last generated by Orchestration Designer at: 16 DE ABRIL DE 2016 18H30MIN56S BRT
 */
public class Operador extends com.avaya.sce.runtime.SubflowReturn {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 16 DE ABRIL DE 2016 18H30MIN56S BRT
	 */
	public Operador() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

}
