package flow.subflow.AutenticarUsuario;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 19 DE ABRIL DE 2016 10H7MIN30S BRT
 */
public class WSAutenticarUsuario extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 19 DE ABRIL DE 2016 10H7MIN30S BRT
	 */
	public WSAutenticarUsuario() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 25 DE ABRIL DE 2016 19H58MIN53S BRT
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = null;
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 25 DE ABRIL DE 2016 19H58MIN53S BRT
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 25 DE ABRIL DE 2016 19H58MIN53S BRT
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(6);
		actions.add(new com.avaya.sce.runtime.varoperations.Assign("WSAutenticarUsuario:SenhaDigitada", "ColetaSenhaResgate:interpretation", false).setDebugId(218));
		actions.add(new com.avaya.sce.runtime.varoperations.Assign("WSAutenticarUsuario:Retorno", "OK", true).setDebugId(177));
		actions.add(new com.avaya.sce.runtime.varoperations.Assign("WSAutenticarUsuario:StatusUser", "desbloqueado", true).setDebugId(178));
		actions.add(new com.avaya.sce.runtime.tracking.TraceInfo(com.avaya.sce.runtimecommon.ITraceInfo.TRACE_LEVEL_DEBUG, "aqui retorno Autenticar Usuario", "WSAutenticarUsuario:Retorno").setDebugId(179));
		actions.add(new com.avaya.sce.runtime.tracking.TraceInfo(com.avaya.sce.runtimecommon.ITraceInfo.TRACE_LEVEL_DEBUG, "aqui status usuario", "WSAutenticarUsuario:StatusUser").setDebugId(180));
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition1", "WSAutenticarUsuario:Retorno", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "OK", false).setDebugId(181)).evaluate(mySession)) {

			if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition2", "WSAutenticarUsuario:StatusUser", com.avaya.sce.runtime.Expression.STRING_NOT_EQUAL_IGNORE, "bloqueado", false).setDebugId(182)).evaluate(mySession)) {
				actions = new java.util.ArrayList(1);
				actions.add(new com.avaya.sce.runtime.Next("AutenticarUsuario-TransOK", "OK").setDebugId(183));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			}


			if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition3", "WSAutenticarUsuario:StatusUser", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "bloqueado", false).setDebugId(204)).evaluate(mySession)) {
				actions = new java.util.ArrayList(1);
				actions.add(new com.avaya.sce.runtime.Next("AutenticarUsuario-AssuntosSenha", "AssuntosSenha").setDebugId(205));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			} else {
				actions = new java.util.ArrayList(2);
				actions.add(new com.avaya.sce.runtime.varoperations.Assign("CheckRetorno", "operador", true).setDebugId(185));
				actions.add(new com.avaya.sce.runtime.Next("AutenticarUsuario-VerificaTentativaNM", "NOK").setDebugId(186));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;
			}


		} else {
			actions = new java.util.ArrayList(2);
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("CheckRetorno", "operador", true).setDebugId(188));
			actions.add(new com.avaya.sce.runtime.Next("AutenticarUsuario-VerificaTentativaNM", "NOK").setDebugId(189));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;
		}


		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
}
