package ingles.phrasesets;

/**
 * This phraseset class will be automatically populated with data from the 
 * phraseset project file.  Manual edits should only be outside of the tag 
 * areas or overridden methods. 
 * Class created on: 
 * Last generated by Orchestration Designer at: 2016-APR-29  09:37:17 PM
 */
public class FrasesMultiplus extends com.avaya.sce.runtime.Phraseset { 

	//{{START:CLASS:FIELDS
	private static final com.avaya.sce.runtime.Phraseset.PhraseMap PHRASE_MAP;
	//}}END:CLASS:FIELDS

	/**
	 * Static initializer
	 */
	static {
		//{{START:PHRASESET:STATIC

		// Create the phrase map, then populate with phrases
		PHRASE_MAP = new com.avaya.sce.runtime.Phraseset.PhraseMap(114);
		com.avaya.sce.runtime.Phrase phrase;

		// phrase: 0a
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "0a", "0a.wav", ""); 

		// phrase: MP0
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "MP0", "MP0.wav", ""); 

		// phrase: MP1
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "MP1", "MP1.wav", ""); 

		// phrase: MP2
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "MP2", "MP2.wav", ""); 

		// phrase: MP3
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "MP3", "MP3.wav", ""); 

		// phrase: MP4
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "MP4", "MP4.wav", ""); 

		// phrase: MP5
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "MP5", "MP5.wav", ""); 

		// phrase: MP9
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "MP9", "MP9.wav", ""); 

		// phrase: MPOuvir
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "MPOuvir", "MPOuvir.wav", ""); 

		// phrase: OpInv
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "OpInv", "OpInv.wav", ""); 

		// phrase: 11d
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "11d", "11d.wav", ""); 

		// phrase: 11e
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "11e", "11e.wav", ""); 

		// phrase: 11f
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "11f", "11f.wav", ""); 

		// phrase: 11i
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "11i", "11i.wav", ""); 

		// phrase: VoltarMenuInicial
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "VoltarMenuInicial", "VoltarMenuInicial.wav", ""); 

		// phrase: SemDuvida
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "SemDuvida", "SemDuvida.wav", ""); 

		// phrase: DigCPF
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "DigCPF", "DigCPF.wav", ""); 

		// phrase: EsqCPF
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "EsqCPF", "EsqCPF.wav", ""); 

		// phrase: 10a
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "10a", "10a.wav", ""); 

		// phrase: 111a
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "111a", "111a.wav", ""); 

		// phrase: 112a
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "112a", "112a.wav", ""); 

		// phrase: 113a
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "113a", "113a.wav", ""); 

		// phrase: VoltarMenuAnterior
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "VoltarMenuAnterior", "VoltarMenuAnterior.wav", ""); 

		// phrase: 21d
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "21d", "21d.wav", ""); 

		// phrase: 21e
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "21e", "21e.wav", ""); 

		// phrase: 21f
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "21f", "21f.wav", ""); 

		// phrase: 21g
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "21g", "21g.wav", ""); 

		// phrase: MPEncer
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "MPEncer", "MPEncer.wav", ""); 

		// phrase: 214a
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "214a", "214a.wav", ""); 

		// phrase: 213a
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "213a", "213a.wav", ""); 

		// phrase: 31a
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "31a", "31a.wav", ""); 

		// phrase: 31b
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "31b", "31b.wav", ""); 

		// phrase: 311d
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "311d", "311d.wav", ""); 

		// phrase: 311f
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "311f", "311f.wav", ""); 

		// phrase: 311e
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "311e", "311e.wav", ""); 

		// phrase: 311g1
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "311g1", "311g1.wav", ""); 

		// phrase: 311g2
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "311g2", "311g2.wav", ""); 

		// phrase: 311g3
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "311g3", "311g3.wav", ""); 

		// phrase: 311g4
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "311g4", "311g4.wav", ""); 

		// phrase: FalarOp
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "FalarOp", "FalarOp.wav", ""); 

		// phrase: 311h
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "311h", "311h.wav", ""); 

		// phrase: 3113f
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "3113f", "3113f.wav", ""); 

		// phrase: 51a
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "51a", "51a.wav", ""); 

		// phrase: 211a
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "211a", "211a.wav", ""); 

		// phrase: DIrOp2
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "DIrOp2", "DirOp2.wav", ""); 

		// phrase: EscolhaLinguagem
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "EscolhaLinguagem", "EscolhaLinguagem.wav", ""); 

		// phrase: 41a
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "41a", "41a.wav", ""); 

		// phrase: 41b
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "41b", "41b.wav", ""); 

		// phrase: 41c
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "41c", "41c.wav", ""); 

		// phrase: 411a
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "411a", "411a.wav", ""); 

		// phrase: 411b
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "411b", "411b.wav", ""); 

		// phrase: DirTAM
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "DirTAM", "DirTAM.wav", ""); 

		// phrase: 114a
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "114a", "114a.wav", ""); 

		// phrase: 114b
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "114b", "114b.wav", ""); 

		// phrase: 3113a
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "3113a", "3113a.wav", ""); 

		// phrase: 3113b
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "3113b", "3113b.wav", ""); 

		// phrase: 3113c
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "3113c", "3113c.wav", ""); 

		//}}END:PHRASESET:STATIC
	}
	/**
	 * Returns the Phrase with the given name.  To override the
	 * behavior and dynamically return a different Phrase object,
	 * override the method "hookGetPhrase(...)".
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 3 DE MAIO DE 2016 17H37MIN10S BRT
	 * @see com.avaya.sce.runtime.Phraseset#getPhrase(String) 
	 */ 
	public com.avaya.sce.runtime.Phrase getPhrase(String phraseName) {
		return(getPhrase(FrasesMultiplus.PHRASE_MAP, phraseName));
	}
}
