/**
 * Last generated by Orchestration Designer at: 16 DE ABRIL DE 2016 18H20MIN36S BRT
 */
package portugues.prompts;

public class AN_ErroTransacao extends com.avaya.sce.runtime.Prompt {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for AN_ErroTransacao.
	 */
	public AN_ErroTransacao() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}


	/**
	 * This method is generated automatically and should not be manually edited
	 * To manually edit the prompt, override:
	 * void updatePrompt()
	 * Last generated by Orchestration Designer at: 16 DE ABRIL DE 2016 18H27MIN2S BRT
	 */
	public void buildPrompt(){
		com.avaya.sce.runtime.Format format = null;
		com.avaya.sce.runtime.RenderHint hint = null;
		com.avaya.sce.runtime.MediaPage mediaPage = null;
		setBarginType(com.avaya.sce.runtimecommon.SCERT.BARGIN_SPEECH);
		setName("AN_ErroTransacao");
		setOrder(com.avaya.sce.runtime.Prompt.STANDARD);

		// Prompt level 1
		setTimeout(1,8000);
		setBargin(1,true);

		if ( new com.avaya.sce.runtime.Condition( "condition", "Idioma", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "portugues", false, null ).evaluate(getSession()) == true ) {
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASESET,"FrasesMultiplus:PT10a",false));
		}

		if ( new com.avaya.sce.runtime.Condition( "condition", "Idioma", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "ingles", false, null ).evaluate(getSession()) == true ) {
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASESET,"FrasesMultiplus:ING10a",false));
		}

		if ( new com.avaya.sce.runtime.Condition( "condition", "Idioma", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "espanhol", false, null ).evaluate(getSession()) == true ) {
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASESET,"FrasesMultiplus:ESP10a",false));
		}

		else {
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASESET,"FrasesMultiplus:PT10a",false));
		}

	}
}
