package flow.subflow.AutenticarUsuario;

import br.com.multiplus.AutenticarUsuario;
import br.com.multiplus.output.AutenticarUsuarioResponse;

/**
 * A basic servlet which allows a user to define their code, generate
 * any output, and to select where to transition to next.
 * Last generated by Orchestration Designer at: 30 DE ABRIL DE 2016 0H50MIN52S BRT
 */
public class WSAutenticarUsuarios extends com.avaya.sce.runtime.BasicServlet {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 30 DE ABRIL DE 2016 0H50MIN52S BRT
	 */
	public WSAutenticarUsuarios() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * This method allows for custom integration with other Java components.
	 * You may use Java for sophisticated logic or to integrate with custom
	 * connectors (i.e. JMS, custom web services, sockets, XML, JAXB, etc.)
	 *
	 * Any custom code added here should work as efficiently as possible to prevent delays.
	 * It's important to design your callflow so that the voice browser (Voice Portal/IR)
	 * is not waiting too long for a response as this can lead to a poor caller experience.
	 * Additionally, if the response to the client voice browser exceeds the configured
	 * timeout, the platform may throw an "error.badfetch". 
	 *
	 * Using this method, you have access to all session variables through the 
	 * SCESession object.
	 *
	 * The code generator will *** NOT *** overwrite this method in the future.
	 * Last generated by Orchestration Designer at: 30 DE ABRIL DE 2016 0H50MIN52S BRT
	 */
	public void servletImplementation(com.avaya.sce.runtimecommon.SCESession mySession) {

		String idUsuario = mySession.getVariable("WSIdentificarParticipante").getComplexVariable().getField("CPFNumMultiplus").getStringValue();
		String senha = mySession.getVariable("WSAutenticarUsuario").getComplexVariable().getField("SenhaDigitada").getStringValue();
		String tpUsuario = mySession.getVariable("WSAutenticarUsuario").getComplexVariable().getField("Usuario").getStringValue();
		String tpCredencial = mySession.getVariable("WSAutenticarUsuario").getComplexVariable().getField("Credencial").getStringValue();
		String endpoint = mySession.getVariable("EndPoints").getComplexVariable().getField("AutenticarUsuario").getStringValue();
		String certificado = mySession.getVariable("CertificadoTransacoes").getSimpleVariable().getStringValue();
		
		AutenticarUsuario api = new AutenticarUsuario();
		AutenticarUsuarioResponse response = null;
		try {
			response = api.apiExecute(idUsuario, senha, endpoint, certificado);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		
		
		if(response.getCodRet().equals("0")){
			//ok
			mySession.getVariable("WSAutenticarUsuario").getComplexVariable().getField("Retorno").setValue(response.getCodRet());
			mySession.getVariable("WSAutenticarUsuario").getComplexVariable().getField("Chave").setValue(response.getChave());
			mySession.getVariable("WSAutenticarUsuario").getComplexVariable().getField("Valor").setValue(response.getValor());
			mySession.getVariable("InMessage").getSimpleVariable().setValue(response.getInMessage());
			mySession.getVariable("OutMessage").getSimpleVariable().setValue(response.getOutMessage());
			
		} else {
			//erro
			mySession.getVariable("WSAutenticarUsuario").getComplexVariable().getField("Retorno").setValue(response.getCodRet());
			mySession.getVariable("WSAutenticarUsuario").getComplexVariable().getField("Mensagem").setValue(response.getMensagem());
			mySession.getVariable("WSAutenticarUsuario").getComplexVariable().getField("Erro").setValue(response.getInstrucao());
			mySession.getVariable("WSAutenticarUsuario").getComplexVariable().getField("Detalhe").setValue(response.getDetalhe());
			mySession.getVariable("InMessage").getSimpleVariable().setValue(response.getInMessage());
			mySession.getVariable("OutMessage").getSimpleVariable().setValue(response.getOutMessage());
		}
		
	}
	/**
	 * Builds the list of branches that are defined for this servlet object.
	 * This list is built automatically by defining Goto nodes in the call flow editor.
	 * It is the programmer's responsibilty to provide at least one enabled Goto.<BR>
	 *
	 * The user should override updateBranches() to determine which Goto that the
	 * framework will activate.  If there is not at least one enabled Goto item, 
	 * the framework will throw a runtime exception.<BR>
	 *
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.  To modify the list
	 * of branches for the flow item, override:
	 *     <code>updateBranches(Collection branches, SCESession mySession)</code>
	 *
	 * @return a Collection of <code>com.avaya.sce.runtime.Goto</code>
	 * objects that will be evaluated at runtime.  If there are no gotos
	 * defined in the Servlet node, then this returns null.
	 * Last generated by Orchestration Designer at: 3 DE MAIO DE 2016 17H37MIN22S BRT
	 */
	public java.util.Collection getBranches(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		com.avaya.sce.runtime.Goto aGoto = null;
		list = new java.util.ArrayList(1);

		aGoto = new com.avaya.sce.runtime.Goto("AutenticarUsuario-TrataAutenticarUsuario", 0, true, "Default");
		list.add(aGoto);

		return list;
	}
}
